services:
  main:
    container_name: notionsnapshot
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace

    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/amd64 ubuntu:20.04

        ARG DEBIAN_FRONTEND=noninteractive

        RUN apt-get update
        RUN apt-get install -y git

        # get selenium chrome driver
        RUN apt-get install -y wget curl unzip
        RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        RUN apt-get install -y ./google-chrome-stable_current_amd64.deb 

        # get python 3.11
        RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && apt install -y python3.11
        RUN apt-get install -y python3-pip

        RUN pip install -r requirements.txt

        CMD ["tail", "-f", "/dev/null"]
